# Generated by Django 4.2.3 on 2023-07-10 14:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pan', models.CharField(max_length=16)),
                ('expiry_date', models.CharField(max_length=5)),
                ('cvv', models.CharField(max_length=3)),
                ('issue_date', models.DateField()),
                ('owner_id', models.CharField(max_length=9)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
    ]
