# Generated by Django 4.2.3 on 2023-07-11 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='pan',
            field=models.CharField(max_length=19),
        ),
    ]
