# Generated by Django 4.2.3 on 2023-07-11 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_alter_card_pan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='pan',
            field=models.CharField(max_length=16),
        ),
    ]
